name: Java CI with Gradle

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle Wrapper
        run: ./gradlew build --configuration-cache-problems=warn --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_DarkCubeUsername: '${{ secrets.REPOSITORY_USERNAME }}'
          ORG_GRADLE_PROJECT_DarkCubePassword: '${{ secrets.REPOSITORY_PASSWORD }}'
